spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

    config:
      enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://${REGISTRY_SERVER_ADRESS}:${REGISTRY_SERVER_PORT}/eureka
      instance:
        preferIpAddress: true
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

server:
  port: 9086
app:
  jwtSecret: ${JWT_SECRET}