spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hatkar/configuration
          clone-on-start: true
server:
  port: 9296